Repository fhswf/MLPro, pull requests merged in 2022-10, with the labels that each got.

#432 BF: Multitasking
  doc/rtd/content/append1/bf/howto.bf.mt.001.rst
  doc/rtd/content/append1/bf/howto.bf.mt.002.rst
  doc/rtd/content/append1/bf/images/howto.bf.mt.001/howto_bf_mt_001_parallel_algorithms.png
  doc/rtd/content/append1/bf/images/howto.bf.mt.002/howto_bf_mt_002_tasks_and_workflows.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/examples/howto_bf_012_processing.py
  src/mlpro/bf/examples/howto_bf_mt_001_parallel_algorithms.py
  src/mlpro/bf/examples/howto_bf_mt_002_tasks_and_workflows.py
  src/mlpro/bf/ml.py
  src/mlpro/bf/mp.py
  src/mlpro/bf/mt.py
  src/mlpro/bf/various.py
Labels: enhancement, BF, next release

#421 BF: Normalizer Classes
  doc/rtd/content/append1/bf/howto.bf.023.rst
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  doc/rtd/content/bf/03_math.rst
  doc/rtd/content/bf/normalizers/normalizers.rst
  src/mlpro/bf/examples/howto_bf_023_normalizers.py
  src/mlpro/bf/math/__init__.py
  src/mlpro/bf/math/basics.py
  src/mlpro/bf/math/normalizers.py
Labels: BF, next release

#447 BF-UI: Fixed dimension access
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio.png
  src/mlpro/bf/examples/howto_bf_009_sciui_reuse_of_interactive_2d_3d_input_space.py
  src/mlpro/bf/math/basics.py
  src/mlpro/bf/ui/sciui/pool/iis.py
  src/mlpro/bf/ui/sciui/pool/iisbenchmark.py
Labels: bug, BF, next release

#451 BF-ML: Class MLTask - Event-based adaptation
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  src/mlpro/bf/ml.py
Labels: enhancement, BF, next release

#454 BF: Refactoring Howtos
  .github/workflows/ci.yml
  doc/rtd/content/append1/bf/data/howto.bf.streams.010.rst
  doc/rtd/content/append1/bf/data/howto.bf.streams.011.rst
  doc/rtd/content/append1/bf/data/howto.bf.streams.012.rst
  doc/rtd/content/append1/bf/eh/howto.bf.eh.001.rst
  doc/rtd/content/append1/bf/howto.bf.002.rst
  doc/rtd/content/append1/bf/howto.bf.003.rst
  doc/rtd/content/append1/bf/howto.bf.004.rst
  doc/rtd/content/append1/bf/howto.bf.005.rst
  doc/rtd/content/append1/bf/howto.bf.006.rst
  doc/rtd/content/append1/bf/howto.bf.007.rst
  doc/rtd/content/append1/bf/howto.bf.008.rst
  doc/rtd/content/append1/bf/howto.bf.011.rst
  doc/rtd/content/append1/bf/howto.bf.020.rst
  doc/rtd/content/append1/bf/howto.bf.021.rst
  doc/rtd/content/append1/bf/howto.bf.022.rst
  doc/rtd/content/append1/bf/howto.bf.023.rst
  doc/rtd/content/append1/bf/math/howto.bf.math.001.rst
  doc/rtd/content/append1/bf/math/howto.bf.math.010.rst
  doc/rtd/content/append1/bf/ml/howto.bf.ml.001.rst
  doc/rtd/content/append1/bf/mt/howto.bf.mt.001.rst
  doc/rtd/content/append1/bf/mt/howto.bf.mt.002.rst
  doc/rtd/content/append1/bf/mt/images/howto.bf.mt.001/howto_bf_mt_001_parallel_algorithms.png
  doc/rtd/content/append1/bf/mt/images/howto.bf.mt.002/howto_bf_mt_002_tasks_and_workflows.png
  doc/rtd/content/append1/bf/ui/howto.bf.ui.001.rst
  doc/rtd/content/append1/bf/ui/images/howto.bf.ui.001/sciui_iis.png
  doc/rtd/content/append1/howto.bf.rst
  doc/rtd/content/append1/rl/howto.bf.ml.002.rst
  doc/rtd/content/append1/rl/howto.bf.ml.003.rst
  doc/rtd/content/append1/rl/howto.rl.ui.002.rst
  doc/rtd/content/append1/rl/images/howto.rl.ui.001/sciui_rl.png
  src/mlpro/bf/examples/howto_bf_001_logging.py
  src/mlpro/bf/examples/howto_bf_002_timer.py
  src/mlpro/bf/examples/howto_bf_003_store_plot_and_save_variables.py
  src/mlpro/bf/examples/howto_bf_004_buffers.py
  src/mlpro/bf/examples/howto_bf_eh_001_event_handling.py
  src/mlpro/bf/examples/howto_bf_math_001_spaces_and_elements.py
  src/mlpro/bf/examples/howto_bf_math_010_normalizers.py
  src/mlpro/bf/examples/howto_bf_ml_001_hyperparameters.py
  src/mlpro/bf/examples/howto_bf_mt_001_parallel_algorithms.py
  src/mlpro/bf/examples/howto_bf_mt_002_tasks_and_workflows.py
  src/mlpro/bf/examples/howto_bf_streams_010_accessing_data_from_openml.py
  src/mlpro/bf/examples/howto_bf_streams_011_accessing_data_from_river.py
  src/mlpro/bf/examples/howto_bf_streams_012_accessing_data_from_scikitlearn.py
  src/mlpro/bf/examples/howto_bf_ui_001_reuse_of_interactive_2d_3d_input_space.py
  src/mlpro/rl/examples/howto_bf_ml_002_hyperparameter_tuning_using_hyperopt.py
  src/mlpro/rl/examples/howto_bf_ml_003_hyperparameter_tuning_using_optuna.py
  src/mlpro/rl/examples/howto_rl_ui_001_reinforcement_learning_cockpit.py
  test/test_examples.py
Labels: documentation, quality, refactoring, BF, next release

#445 BF-MT: Fixes and enhancements
  .github/workflows/ci.yml
  doc/rtd/content/append1/bf/mt/howto.bf.mt.001.rst
  doc/rtd/content/append1/bf/mt/howto.bf.mt.002.rst
  doc/rtd/content/append1/bf/mt/images/howto.bf.mt.001/howto_bf_mt_001_parallel_algorithms.png
  doc/rtd/content/append1/bf/mt/images/howto.bf.mt.002/howto_bf_mt_002_tasks_and_workflows.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio.png
  src/mlpro/bf/examples/howto_bf_mt_001_parallel_algorithms.py
  src/mlpro/bf/examples/howto_bf_mt_002_tasks_and_workflows.py
  src/mlpro/bf/mt.py
  test/test_examples.py
Labels: bug, enhancement, BF, next release

#467 BF-Math: Z-transform update - parameter update based on single new data instance
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math-Normalizers_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio.png
  src/mlpro/bf/examples/howto_bf_math_010_normalizers.py
  src/mlpro/bf/math/normalizers.py
Labels: enhancement, OA, BF, next release

#469 RTD: Basic Functions
  doc/rtd/content/bf/01_overview.rst
  doc/rtd/content/bf/images/MLPro-BF_Overview.drawio
  doc/rtd/content/bf/images/MLPro-BF_Overview.drawio.png
Labels: documentation, BF, next release

#480 BF: Extensions of class Dimension
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio.png
  src/mlpro/bf/math/basics.py
  test/test_examples.py
Labels: BF, next release

#477 BF: Plot extensions
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Plot_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio_1.dtmp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/plot.py
Labels: enhancement, BF, next release

#482 BF-Streams: Enhancements
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math-Normalizers_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Plot_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Various_class_diagram.drawio_1.dtmp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio.png
  src/mlpro/bf/math/basics.py
  src/mlpro/bf/pool/__init__.py
  src/mlpro/bf/pool/streams/__init__.py
  src/mlpro/bf/streams/__init__.py
  src/mlpro/bf/streams/models.py
  src/mlpro/bf/streams/native.py
Labels: enhancement, BF, next release

#491 BF: New module bf.ops
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-OPS_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-OPS_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/ml.py
  src/mlpro/bf/ops.py
  src/mlpro/bf/plot.py
  src/mlpro/bf/streams/models.py
  src/mlpro/bf/various.py
Labels: enhancement, BF

#493 BF-ML/-Plot: Refactoring
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio.png
  src/mlpro/bf/ml.py
  src/mlpro/bf/plot.py
Labels: refactoring, BF, next release
