Repository fhswf/MLPro, pull requests merged in 2022-11, with the labels that each got.

#409 OA - Online adaptivity (preparation)
  doc/rtd/content/append1/bf/data/howto.bf.streams.010.rst
  doc/rtd/content/append1/bf/data/howto.bf.streams.011.rst
  doc/rtd/content/append1/bf/data/howto.bf.streams.012.rst
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/oa/.$MLPro-OA-Proc_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/oa/MLPro-OA-CLU_class_diagram.drawio
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/oa/MLPro-OA-SCIUI_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.png
  doc/rtd/content/append2/core/mlpro.oa.rst
  doc/rtd/content/append2/core/mlpro.rl.rst
  src/mlpro/bf/examples/howto_bf_streams_001_tasks_workflows_and_stream_scenarios.py
  src/mlpro/bf/ml.py
  src/mlpro/bf/mt.py
  src/mlpro/bf/ops.py
  src/mlpro/bf/plot.py
  src/mlpro/bf/streams/__init__.py
  src/mlpro/bf/streams/models.py
  src/mlpro/bf/streams/tasks/__init__.py
  src/mlpro/bf/streams/tasks/windows.py
  src/mlpro/gt/__init__.py
  src/mlpro/gt/examples/howto_gt_dp_001_run_multi_player_with_own_policy_on_multicartpole_game_board.py
  src/mlpro/gt/examples/howto_gt_dp_002_train_own_multi_player_on_multicartpole_game_board.py
  src/mlpro/gt/models.py
  src/mlpro/oa/__init__.py
  src/mlpro/oa/models.py
  src/mlpro/oa/pool/tasks/__init__.py
  src/mlpro/oa/pool/tasks/boundarydetectors.py
  src/mlpro/rl/__init__.py
  src/mlpro/rl/examples/howto_rl_001_reward.py
  src/mlpro/rl/examples/howto_rl_agent_001_run_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_002_train_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_003_run_multiagent_with_own_policy_on_multicartpole_environment.py
  src/mlpro/rl/examples/howto_rl_agent_004_train_multiagent_with_own_policy_on_multicartpole_environment.py
  src/mlpro/rl/examples/howto_rl_agent_005_train_and_reload_single_agent.py
  src/mlpro/rl/examples/howto_rl_att_001_advanced_training_with_stagnation_detection.py
  src/mlpro/rl/examples/howto_rl_att_002_train_wrapped_sb3_policy_with_stagnation_detection.py
  src/mlpro/rl/examples/howto_rl_env_001_train_agent_with_sb3_policy_on_ur5_environment.py
  src/mlpro/rl/examples/howto_rl_env_002_train_agent_with_SB3_policy_on_robothtm_environment.py
  src/mlpro/rl/examples/howto_rl_env_003_train_agent_with_sb3_policy_on_multigeo_environment.py
  src/mlpro/rl/examples/howto_rl_wp_003_run_multiagent_with_own_policy_on_petting_zoo_environment.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_sar.py
  src/mlpro/rl/models_train.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
Labels: enhancement, OA, next release

#503 Bug fixing howto_rl_wp
  src/mlpro/rl/examples/howto_rl_wp_001_mlpro_environment_to_gym_environment.py
  src/mlpro/rl/examples/howto_rl_wp_002_mlpro_environment_to_petting_zoo_environment.py
  src/mlpro/rl/examples/howto_rl_wp_003_run_multiagent_with_own_policy_on_petting_zoo_environment.py
Labels: bug, RL, next release

#502 BF-ML: Refactoring
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  src/mlpro/bf/ml.py
  src/mlpro/gt/examples/howto_gt_dp_001_run_multi_player_with_own_policy_on_multicartpole_game_board.py
  src/mlpro/gt/examples/howto_gt_dp_002_train_own_multi_player_on_multicartpole_game_board.py
  src/mlpro/rl/examples/howto_rl_agent_001_run_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_002_train_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_003_run_multiagent_with_own_policy_on_multicartpole_environment.py
  src/mlpro/rl/examples/howto_rl_agent_004_train_multiagent_with_own_policy_on_multicartpole_environment.py
  src/mlpro/rl/examples/howto_rl_ht_001_hyperopt.py
  src/mlpro/rl/examples/howto_rl_ht_002_optuna.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/policies/dummy.py
  src/mlpro/rl/pool/policies/randomgenerator.py
  src/mlpro/sl/__init__.py
  src/mlpro/sl/models.py
  src/mlpro/wrappers/sb3.py
  test/test_sb3_policy_wrapper.py
Labels: refactoring, BF, next release

#510 BF-Ops: Refactoring
  src/mlpro/bf/ops.py
  src/mlpro/rl/models_train.py
Labels: refactoring, RL, BF, next release

#435 SL: Initial design
  doc/rtd/content/append2/core/images/sl/MLPro-SL_class_diagram.drawio
  doc/rtd/content/append2/core/images/sl/MLPro-SL_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/sl/MLPro-SL_class_diagram.png
  doc/rtd/content/append2/core/mlpro.sl.rst
Labels: enhancement, SL, v3.0.0

#513 BF-Streams
  src/mlpro/bf/examples/howto_bf_streams_010_accessing_data_from_openml.py
  src/mlpro/bf/examples/howto_bf_streams_011_accessing_data_from_river.py
  src/mlpro/bf/examples/howto_bf_streams_012_accessing_data_from_scikitlearn.py
  src/mlpro/wrappers/openml.py
  src/mlpro/wrappers/river.py
  src/mlpro/wrappers/sklearn.py
  test/test_examples.py
Labels: enhancement, BF, next release

#515 RL: Refactoring
  doc/rtd/content/append2/core/images/rl/02_environments/.$MLPro-RL-Env_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/rl/02_environments/.$MLPro-RL-Env_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio.png
  src/mlpro/bf/ml.py
  src/mlpro/bf/plot.py
  src/mlpro/rl/examples/howto_rl_env_002_train_agent_with_SB3_policy_on_robothtm_environment.py
  src/mlpro/rl/examples/howto_rl_ht_001_hyperopt.py
  src/mlpro/rl/examples/howto_rl_ht_002_optuna.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envs/bglp.py
  src/mlpro/rl/pool/envs/robotinhtm.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
Labels: refactoring, RL, next release

#495 Add Download Stats
  README.md
Labels: documentation, admin, next release

#398 RL Solution for Double Pendulum Env.
  src/mlpro/bf/ml.py
  src/mlpro/bf/plot.py
  src/mlpro/rl/examples/howto_rl_022_validating_dp.py
  src/mlpro/rl/examples/howto_rl_env_004_run_agent_with_random_actions_on_double_pendulum_environment.py
  src/mlpro/rl/examples/howto_rl_env_005_train_agent_with_sb3_policy_on_double_pendulum_environment.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/pool/envs/doublependulum.py
Labels: enhancement, v1.0.0, RL

#505 BF-Math-Normalizers: Update parameters of Z-transofrmer with a replaced element
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math-Normalizers_class_diagram.drawio.png
  src/mlpro/bf/examples/howto_bf_math_010_normalizers.py
  src/mlpro/bf/math/normalizers.py
Labels: enhancement, BF, next release

#471 RTD: Basic functions
  doc/rtd/content/append2/core/images/bf/MLPro-BF_Overview.drawio.png
  doc/rtd/content/bf/images/MLPro-BF_Overview.drawio
  doc/rtd/content/bf/images/MLPro-BF_Overview.drawio.png
Labels: documentation, BF, next release

#523 BF-ML: New abstract class AdaptiveFunction #522
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/sl/MLPro-SL_class_diagram.drawio
  doc/rtd/content/append2/core/images/sl/MLPro-SL_class_diagram.drawio.png
  src/mlpro/bf/ml.py
  src/mlpro/sl/models.py
  src/mlpro/sl/pool/afct/afct_pytorch.py
Labels: refactoring, BF, next release

#540 RTD: Cleanup
  doc/rtd/_static/custom.css
  doc/rtd/_static/favicon.ico
  doc/rtd/_static/logo_mlpro.png
  doc/rtd/content/append2/wrappers/openai_gym.rst
  doc/rtd/content/append2/wrappers/sb3.rst
  doc/rtd/content/rl/env/pool/doublependulum.rst
  doc/rtd/content/rl/env/pool/multicartpole.rst
  doc/rtd/content/rl/env/pool/robotmanipulator.rst
  doc/rtd/content/sl/02_adaptive_function.rst
Labels: documentation, admin, next release

#386 Simulation of MPPS
  test/test_buffer.py
  test/test_environment.py
  test/test_math.py
  test/test_pool_policies.py
  test/test_sb3_policy_wrapper.py
  test/test_various.py
Labels: enhancement, v2.0.0, RL, GT

#550 BF: New base class FctSTrans
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-MT_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Streams_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Systems_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Systems_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Systems_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF_Overview.drawio.png
  doc/rtd/content/append2/core/images/rl/01_environments/MLPro-RL-Env-Ada_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/01_environments/MLPro-RL-Env-Ada_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/01_environments/MLPro-RL-Env_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/01_environments/MLPro-RL-Env_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/01_state-action-reward/MLPro-RL-SAR_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/01_state-action-reward/MLPro-RL-SAR_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/02_agents/MLPro-RL-Agents_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/02_agents/MLPro-RL-Agents_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/02_environments/.$MLPro-RL-Env_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/rl/02_environments/.$MLPro-RL-Env_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/02_environments/MLPro-RL-Env_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/03_run_and_train/MLPro-RL-Train_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/03_run_and_train/MLPro-RL-Train_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  doc/rtd/content/append2/core/mlpro.rl.rst
  src/mlpro/bf/systems.py
  src/mlpro/rl/examples/howto_rl_agent_001_run_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_mb_002_grid_world_environment.py
  src/mlpro/rl/models.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_env_ada.py
  src/mlpro/rl/models_sar.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envs/gridworld.py
  src/mlpro/rl/pool/envs/multicartpole.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
Labels: enhancement, RL, BF, next release

#547 BF: Streams
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio.png
  src/mlpro/bf/examples/howto_bf_streams_103_stream_task_window.py
  src/mlpro/bf/streams/tasks/windows.py
Labels: enhancement, BF, next release
