Repository fhswf/MLPro, pull requests merged in 2022-05, with the labels that each got.

#328 Wrapper Gym Enhancement
  .github/workflows/python37.yml
  .github/workflows/python38.yml
  .github/workflows/python39.yml
  src/mlpro/wrappers/openai_gym.py
Labels: bug, RL, v0.9.0

#329 Release of first version of random generator policy
  examples/rl/Howto 08 - (RL) Run own agents with petting zoo environment.py
  examples/rl/Howto 17 - (RL) Advanced training with stagnation detection.py
  src/mlpro/rl/pool/policies/randomgenerator.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
  test/test_pool_policies.py
Labels: enhancement, RL, GT, v0.9.0

#339 Automate Build UR5 ROS Workspace
  examples/rl/Howto 14a - (RL) Train UR5 with SB3 wrapper.py
  src/mlpro/rl/pool/envs/ur5jointcontrol/ur5jointcontrol.py
Labels: enhancement

#340 Add gazebo visualization GUI toggle for UR5
  examples/rl/Howto 14a - (RL) Train UR5 with SB3 wrapper.py
  src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/openai_ros/openai_ros/src/openai_ros/openai_ros_common.py
  src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/openai_ros/openai_ros/src/openai_ros/task_envs/ur5_lab/simple_task.py
Labels: enhancement

#341 Bglp update
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envs/bglp.py
Labels: bug

#350 Bglp
  src/mlpro/rl/pool/envs/bglp.py
Labels: enhancement, RL

#351 SB3 Wrapper: Enable the possibility to process reward type C_TYPE_EVERY_AGENT
  src/mlpro/wrappers/sb3.py
Labels: enhancement, refactoring, RL
