Repository fhswf/MLPro, pull requests merged in 2022-08, with the labels that each got.

#371 Root class Wrapper
  doc/rtd/content/append1/oa/howto.oa.002.rst
  doc/rtd/content/append2/mlpro.wrappers.rst
  doc/rtd/content/append2/wrappers/hyperopt.rst
  doc/rtd/content/append2/wrappers/mlpro.rl.wrappers.rst
  doc/rtd/content/append2/wrappers/openai_gym.rst
  doc/rtd/content/append2/wrappers/openml.rst
  doc/rtd/content/append2/wrappers/optuna.rst
  doc/rtd/content/append2/wrappers/pettingzoo.rst
  doc/rtd/content/append2/wrappers/river.rst
  doc/rtd/content/append2/wrappers/sb3.rst
  doc/rtd/content/append2/wrappers/sklearn.rst
  src/mlpro/bf/various.py
  src/mlpro/rl/examples/howto_rl_002_run_agent_with_own_policy_with_gym_environment.py
  src/mlpro/rl/examples/howto_rl_008_wrap_mlpro_environment_to_gym_environment.py
  src/mlpro/wrappers/hyperopt.py
  src/mlpro/wrappers/models.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/openml.py
  src/mlpro/wrappers/optuna.py
  src/mlpro/wrappers/pettingzoo.py
  src/mlpro/wrappers/river.py
  src/mlpro/wrappers/sb3.py
  src/mlpro/wrappers/sklearn.py
Labels: v1.0.0, BF

#379 BF: Event handling
  doc/rtd/content/append1/bf/howto.bf.011.rst
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Events_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Events_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/~$MLPro-BF-Events_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/data.py
  src/mlpro/bf/events.py
  src/mlpro/bf/examples/howto_bf_011_event_handling.py
  src/mlpro/bf/exceptions.py
  src/mlpro/bf/math.py
  src/mlpro/bf/plot.py
  src/mlpro/bf/various.py
Labels: enhancement, v1.0.0, BF

#366 Action Planner using MPC
  src/mlpro/rl/examples/howto_rl_013_model_based_reinforcement_learning.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/pool/actionplanner/mpc.py
  src/mlpro/sl/models.py
Labels: enhancement, v1.0.0, RL

#381 BF.ML.Model: Event Handling
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.png
  doc/rtd/content/append2/core/images/bf/~$MLPro-BF-ML_class_diagram.drawio.bkp
  src/mlpro/bf/ml.py
Labels: enhancement, v1.0.0, BF

#385 Updating BGLP
  src/mlpro/rl/pool/envs/bglp.py
Labels: enhancement, v1.0.0, RL, GT
