Repository fhswf/MLPro, pull requests merged in 2022-01, with the labels that each got.

#239 Model Improvements 8
  doc/rtd/content/append2/core/images/rl/03_agents/MLPro-RL-Agents_class_diagram.drawio
  doc/rtd/content/append2/core/images/rl/03_agents/MLPro-RL-Agents_class_diagram.png
  doc/rtd/content/append3/images/logo_fh-at.png
  examples/rl/Howto 16 - (RL) Model Based Reinforcement Learning.py
  src/mlpro/bf/ml.py
  src/mlpro/bf/various.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envmodels/mlp_robotinhtm.py
  src/mlpro/sl/pool/afct/afctrans_mlp_robotinhtm.py
  src/mlpro/sl/pool/afct/afctrans_pytorch.py
  test/test_examples.py
Labels: enhancement, Rel. 1.0.0

#259 Ur5 fix and SB3 fixed using 1.3.0
  .github/workflows/python37.yml
  .github/workflows/python38.yml
  .github/workflows/python39.yml
  examples/rl/Howto 14 - (RL) Train UR5 with SB3 wrapper.py
  examples/rl/Howto 18 - (RL) Single Agent with stagnation detection and SB3 Wrapper.py
  src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/ur5_lab/config/ur5_simple_task_param.yaml
  src/mlpro/rl/pool/envs/ur5jointcontrol/ur5jointcontrol.py
  src/mlpro/wrappers/openai_gym.py
  test/test_examples.py
  test/test_sb3_policy_wrapper.py
Labels: bug, refactoring

#263 fix sb3
  .github/workflows/python37.yml
  .github/workflows/python38.yml
  .github/workflows/python39.yml
  src/mlpro/wrappers/sb3.py
Labels: bug

#262 PettingZoo Wrapper Update
  src/mlpro/wrappers/pettingzoo.py
Labels: enhancement

#264 OpenAi gym wrapper, SB3 test script, robotinhtm env
  src/mlpro/rl/pool/envs/robotinhtm.py
  src/mlpro/wrappers/openai_gym.py
  test/test_sb3_policy_wrapper.py
Labels: bug, enhancement

#266 Model improvements #9
  examples/bf/Howto 07 - (ML) Hyperparameter Tuning using Hyperopt.py
  examples/rl/Howto 17 - (RL) Advanced training with stagnation detection.py
  src/mlpro/bf/math.py
  src/mlpro/bf/pool/__init__.py
  src/mlpro/bf/pool/trendanalyzer/__init__.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envs/bglp.py
  src/mlpro/wrappers/hyperopt.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
Labels: bug, enhancement, v1.0.0

#270 RL-Train: turned off training data logging on eval
  src/mlpro/rl/models_train.py
Labels: bug, v1.0.0

#273 Use deterministic for evaluation
  examples/rl/Howto 14 - (RL) Train UR5 with SB3 wrapper.py
  examples/rl/Howto 15 - (RL) Train Robothtm with SB3 Wrapper.py
  examples/rl/Howto 18 - (RL) Single Agent with stagnation detection and SB3 Wrapper.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_sar.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envs/robotinhtm.py
  src/mlpro/wrappers/sb3.py
  test/test_sb3_policy_wrapper.py
Labels: bug

#268 Hyperopt wrapper + bglp update
  examples/bf/Howto 07 - (ML) Hyperparameter Tuning using Hyperopt.py
  src/mlpro/bf/ml.py
  src/mlpro/rl/pool/envs/bglp.py
  src/mlpro/wrappers/hyperopt.py
Labels: enhancement, v1.0.0

#274 Hyperopt
  src/mlpro/wrappers/hyperopt.py
Labels: enhancement, v1.0.0

#281 Hyperopt DataStoring
  src/mlpro/bf/ml.py
  src/mlpro/wrappers/hyperopt.py
Labels: enhancement, v1.0.0

#282 Update _adapt method in MultiAgent class
  src/mlpro/rl/models_agents.py
Labels: enhancement, v1.0.0
