Repository fhswf/MLPro, pull requests merged in 2022-09, with the labels that each got.

#394 Renaming maturity to accuracy
  src/mlpro/bf/ml.py
  src/mlpro/gt/models.py
  src/mlpro/wrappers/models.py
Labels: refactoring, BF, 0.9.2

#323 Double pendulum environment
  doc/rtd/content/append1/rl/howto.rl.020.rst
  doc/rtd/content/append1/rl/images/double_pendulum.gif
  doc/rtd/content/append2/pool/rl/images/MPro-RL-DoublePendulum-class-diagram.drawio
  doc/rtd/content/append2/pool/rl/images/MPro-RL-DoublePendulum-class-diagram.drawio.png
  doc/rtd/content/append2/pool/rl/mlpro.rl.pool.envs.rst
  doc/rtd/content/rl/env/customenv.rst
  doc/rtd/content/rl/env/pool/doublependulum.rst
  doc/rtd/content/rl/env/pool/images/doublependulum.gif
  doc/rtd/content/rl/env/pool/images/doublependulum_run.gif
  src/mlpro/rl/examples/howto_rl_020_run_double_pendulum_with_random_actions.py
  src/mlpro/rl/examples/howto_rl_021_train_wrapped_sb3_policy_on_doublependulum.py
  src/mlpro/rl/pool/envs/doublependulum.py
  test/test_environment.py
  test/test_examples.py
Labels: enhancement, RL, 0.9.2

#397 Conda build
  .github/workflows/conda_deploy.yml
  README.md
  src/build/lib/mlpro/__init__.py
  src/conda/conda_build_config.yaml
  src/conda/meta.yaml
Labels: admin

#393 BF: Multiprocessing
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/~$MLPro-BF-Events_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/~$MLPro-BF-ML_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/examples/howto_bf_012_processing.py
  src/mlpro/bf/mp.py
Labels: enhancement, BF

#383 online_adaptivity3
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/oa/~$MLPro-OA-Proc_class_diagram.drawio.bkp
  src/mlpro/oa/pool/processing/__init__.py
  src/mlpro/oa/pool/steps/__init__.py
Labels: OA

#401 MLPro-OA: initial class design
  doc/rtd/content/append2/core/images/oa/.$MLPro-OA-Proc_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/oa/.$MLPro-OA-Streams_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/oa/.$MLPro-OA-Streams_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio
  doc/rtd/content/append2/core/images/oa/~$MLPro-OA-Proc_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/oa/~$MLPro-OA-Streams_class_diagram.drawio.bkp
Labels: 0.9.2

#403 BF Extensions
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-ML_class_diagram.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  src/mlpro/bf/ml.py
Labels: 0.9.2

#404 BF Extensions(2)
  doc/rtd/content/append1/bf/howto.bf.020.rst
  doc/rtd/content/append1/bf/howto.bf.021.rst
  doc/rtd/content/append1/bf/howto.bf.022.rst
  doc/rtd/content/append1/oa/howto.oa.001.rst
  doc/rtd/content/append1/oa/howto.oa.002.rst
  doc/rtd/content/append1/oa/howto.oa.003.rst
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Math_class_diagram.drawio.dtmp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MP_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Various_class_diagram.drawio.png
  doc/rtd/content/append2/core/mlpro.bf.rst
  doc/rtd/content/append2/core/mlpro.oa.rst
  doc/rtd/content/append2/pool/rl/mlpro.rl.pool.envs.rst
  doc/rtd/content/append2/wrappers/openml.rst
  doc/rtd/content/append2/wrappers/river.rst
  doc/rtd/content/append2/wrappers/sklearn.rst
  src/mlpro/bf/examples/howto_bf_020_accessing_data_from_openml.py
  src/mlpro/bf/examples/howto_bf_021_accessing_data_from_river.py
  src/mlpro/bf/examples/howto_bf_022_accessing_data_from_scikitlearn.py
  src/mlpro/bf/math.py
  src/mlpro/bf/mp.py
  src/mlpro/bf/pool/streams/__init__.py
  src/mlpro/bf/pool/streams/native.py
  src/mlpro/bf/pool/trendanalyzer/__init__.py
  src/mlpro/bf/streams.py
  src/mlpro/oa/models.py
  src/mlpro/oa/models_proc.py
  src/mlpro/wrappers/openml.py
  src/mlpro/wrappers/river.py
  src/mlpro/wrappers/sklearn.py
Labels: 0.9.2

#392 RTD Documentation (Heckathon - 26/08/2022 and 02/09/2022)
  doc/rtd/_static/custom.css
  doc/rtd/_static/favicon.ico
  doc/rtd/_static/logo_mlpro.png
  doc/rtd/content/bf/elementary/images/log_example.png
  doc/rtd/content/bf/elementary/images/log_structure.png
  doc/rtd/content/bf/elementary/log.rst
  doc/rtd/content/gt/01_overview.rst
  doc/rtd/content/gt/03_gameboard.rst
  doc/rtd/content/gt/04_getstarted.rst
  doc/rtd/content/intro/getstarted.rst
  doc/rtd/content/intro/overview copy.rst
  doc/rtd/content/intro/overview.rst
  doc/rtd/content/oa/02_getstarted.rst
  doc/rtd/content/rl/01_overview.rst
  doc/rtd/content/rl/02_env.rst
  doc/rtd/content/rl/03_agents.rst
  doc/rtd/content/rl/06_wrapper.rst
  doc/rtd/content/rl/07_getstarted.rst
  doc/rtd/content/rl/agents/custompolicies.rst
  doc/rtd/content/rl/agents/images/.$MLPro-RL-Agents_flowchart_adaptation.drawio.bkp
  doc/rtd/content/rl/agents/images/MLPro-RL-Agents_flowchart_adaptation.drawio
  doc/rtd/content/rl/agents/images/MLPro-RL-Agents_flowchart_adaptation.png
  doc/rtd/content/rl/agents/pool.rst
  doc/rtd/content/rl/agents/pool/randomaction.rst
  doc/rtd/content/rl/env/customenv.rst
  doc/rtd/content/rl/env/envmodel.rst
  doc/rtd/content/rl/getstarted/mb_rl.rst
  doc/rtd/content/rl/getstarted/mf_rl.rst
  doc/rtd/content/rl/images/MLPro-RL_agents.png
  doc/rtd/content/rl/images/MLPro-RL_overview.png
  doc/rtd/index.rst
Labels: documentation, 0.9.2

#410 Autodoc Generation CI
  .github/workflows/ci.yml
  .github/workflows/doc_gen.yml
  doc/rtd/content/append4/mlpro.bf.examples.rst
  doc/rtd/content/append4/mlpro.bf.pool.rst
  doc/rtd/content/append4/mlpro.bf.pool.streams.rst
  doc/rtd/content/append4/mlpro.bf.rst
  doc/rtd/content/append4/mlpro.bf.ui.rst
  doc/rtd/content/append4/mlpro.bf.ui.sciui.pool.rst
  doc/rtd/content/append4/mlpro.bf.ui.sciui.rst
  doc/rtd/content/append4/mlpro.bf.ui.sciui.templates.rst
  doc/rtd/content/append4/mlpro.gt.examples.rst
  doc/rtd/content/append4/mlpro.gt.pool.boards.rst
  doc/rtd/content/append4/mlpro.gt.pool.rst
  doc/rtd/content/append4/mlpro.gt.rst
  doc/rtd/content/append4/mlpro.oa.examples.rst
  doc/rtd/content/append4/mlpro.oa.pool.rst
  doc/rtd/content/append4/mlpro.oa.pool.steps.rst
  doc/rtd/content/append4/mlpro.oa.rst
  doc/rtd/content/append4/mlpro.oa.sciui.rst
  doc/rtd/content/append4/mlpro.rl.examples.rst
  doc/rtd/content/append4/mlpro.rl.pool.actionplanner.rst
  doc/rtd/content/append4/mlpro.rl.pool.envmodels.rst
  doc/rtd/content/append4/mlpro.rl.pool.envs.multigeorobot.rst
  doc/rtd/content/append4/mlpro.rl.pool.envs.rst
  doc/rtd/content/append4/mlpro.rl.pool.envs.ur5jointcontrol.rst
  doc/rtd/content/append4/mlpro.rl.pool.policies.rst
  doc/rtd/content/append4/mlpro.rl.pool.rst
  doc/rtd/content/append4/mlpro.rl.pool.sarsbuffer.rst
  doc/rtd/content/append4/mlpro.rl.pool.scenarios.rst
  doc/rtd/content/append4/mlpro.rl.rst
  doc/rtd/content/append4/mlpro.rst
  doc/rtd/content/append4/mlpro.sl.examples.rst
  doc/rtd/content/append4/mlpro.sl.pool.afct.rst
  doc/rtd/content/append4/mlpro.sl.pool.rst
  doc/rtd/content/append4/mlpro.sl.rst
  doc/rtd/content/append4/mlpro.wrappers.rst
Labels: enhancement

#414 SB3: HER Implementation
  src/mlpro/wrappers/sb3.py
Labels: enhancement, wrapper, next release

#437 Minor improvement: _extract_observation method (Agent class) + PettingZoo
  src/mlpro/rl/models_agents.py
  src/mlpro/wrappers/pettingzoo.py
Labels: bug, enhancement, RL, next release
