Repository fhswf/MLPro, pull requests merged in 2022-03, with the labels that each got.

#292 Model improvements15
  examples/bf/Howto 03 - (Math) Spaces, subspaces and elements.py
  examples/bf/Howto 05 - (ML) Hyperparameters setup.py
  examples/bf/Howto 07 - (ML) Hyperparameter Tuning using Hyperopt.py
  examples/gt/Howto 06 - (GT) Run multi-player with own policy in multicartpole game board.py
  examples/gt/Howto 07 - (GT) Train own multi-player with multicartpole game board.py
  examples/rl/Howto 04 - (RL) Run multi-agent with own policy in multicartpole environment.py
  examples/rl/Howto 05 - (RL) Train multi-agent with own policy on multicartpole environment.py
  examples/rl/Howto 08 - (RL) Run own agents with petting zoo environment.py
  examples/rl/Howto 10 - (RL) Train using SB3 Wrapper.py
  examples/rl/Howto 13 - (RL) Comparison Native and Wrapper SB3 Policy.py
  examples/rl/Howto 17 - (RL) Advanced training with stagnation detection.py
  examples/rl/Howto 19 - (RL) Comparison Native and Wrapper SB3 Off-Policy.py
  src/mlpro/bf/math.py
  src/mlpro/bf/ml.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/models_env.py
  src/mlpro/rl/models_sar.py
  src/mlpro/rl/models_train.py
  src/mlpro/rl/pool/envmodels/mlp_robotinhtm.py
  src/mlpro/rl/pool/envs/bglp.py
  src/mlpro/rl/pool/envs/doublependulum.py
  src/mlpro/rl/pool/envs/gridworld.py
  src/mlpro/rl/pool/envs/multicartpole.py
  src/mlpro/rl/pool/envs/multigeorobot/multigeorobot.py
  src/mlpro/rl/pool/envs/robotinhtm.py
  src/mlpro/wrappers/hyperopt.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/pettingzoo.py
  src/mlpro/wrappers/sb3.py
  test/test_examples.py
  test/test_sb3_policy_wrapper.py
Labels: enhancement, RL, BF

#302 Refactoring due to PettingZoo version 1.17.0
  .github/workflows/python37.yml
  .github/workflows/python38.yml
  .github/workflows/python39.yml
  src/mlpro/wrappers/pettingzoo.py
Labels: bug, enhancement, v1.0.0

#303 Optuna Wrapper Class
  examples/bf/Howto 08 - (ML) Hyperparameter Tuning using Optuna.py
  src/mlpro/wrappers/hyperopt.py
  src/mlpro/wrappers/optuna.py
Labels: enhancement, v1.0.0

#305 Optuna Wrapper: Change methods names
  src/mlpro/wrappers/hyperopt.py
  src/mlpro/wrappers/optuna.py
Labels: enhancement
