Repository fhswf/MLPro, pull requests merged in 2023-09, with the labels that each got.

#796 Marketplace for MLPro
  .github/workflows/marketplace.yml
Labels: admin, next release

#797 Marketplace for MLPro (2)
  .github/workflows/marketplace.yml
Labels: admin, next release

#799 Marketplace for MLPro (4)
  .github/workflows/ci.yml
  .github/workflows/conda_deploy.yml
  .github/workflows/history/docker_deploy.yml
  .github/workflows/marketplace.yml
  .github/workflows/pypi_deploy.yml
Labels: admin

#800 Marketplace for MLPro (5)
  .github/workflows/marketplace.yml
Labels: admin

#801 Marketplace for MLPro (6)
  .github/workflows/assign_project.yml
  .github/workflows/marketplace.yml
  marketplace/update_marketplace.py
Labels: admin

#804 Marketplace for MLPro (7)
  .github/workflows/assign_project.yml
Labels: admin

#806 Marketplace for MLPro (8)
  .github/workflows/assign_project.yml
  marketplace/update_marketplace.py
Labels: admin

#834 Marketplace for MLPro (9)
  marketplace/templates/issue_body
  marketplace/templates/issue_comment
  marketplace/templates/rtd_extension
  marketplace/update_marketplace.py
Labels: admin

#835 Marketplace for MLPro (10)
  .github/workflows/marketplace.yml
  doc/rtd/content/04_marketplace/01_extensions_org/main.rst
  doc/rtd/content/04_marketplace/01_intro.rst
  doc/rtd/content/04_marketplace/02_extensions.rst
  doc/rtd/content/04_marketplace/02_extensions_user/main.rst
  doc/rtd/index.rst
  generated.txt
  marketplace/templates/rtd_ext_owner.rst
  marketplace/templates/rtd_ext_repo.rst
  marketplace/templates/rtd_extension
  marketplace/update_marketplace.py
  marketplace/whitelist
Labels: admin

#846 RTD cleanup (2)
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_rl/att/howto.rl.att.003.rst.disabled
  test/test_examples.py
Labels: bug, documentation, admin

#848 RTD cleanup (3)
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_rl/ht/howto.rl.ht.001.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_rl/ht/howto.rl.ht.002.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_rl/mb/howto.rl.mb.001.rst.disabled
Labels: bug, documentation, admin

#849 RTD cleanup (4)
  .readthedocs.yaml
  doc/rtd/conda_env.yml
  doc/rtd/requirements.txt
Labels: bug, documentation, admin

#857 Marketplace for MLPro (12)
  .github/workflows/extension_hub.yml
  doc/rtd/content/04_extensions/main.rst
  doc/rtd/content/04_extensions/sub/01_extensions_org/main.rst
  doc/rtd/content/04_extensions/sub/01_extensions_org/org/fhswf.rst
  doc/rtd/content/04_extensions/sub/01_extensions_org/org/fhswf/MLPro-MPPS.rst
  doc/rtd/content/04_extensions/sub/01_intro.rst
  doc/rtd/content/04_extensions/sub/02_extensions.rst
  doc/rtd/content/04_extensions/sub/02_extensions_user/main.rst
  doc/rtd/index.rst
  extensions/update_extension_hub.py
  extensions/whitelist
Labels: documentation, admin, v1.2.0

#858 BF - Bug Fix in Howto for Normalizers
  src/mlpro/bf/examples/howto_bf_math_010_normalizers.py
Labels: bug, BF, v1.2.0

#860 Bug: RTD - PDF generation fails #851
  .readthedocs.yaml
Labels: bug, v1.2.0

#867 Release 1.2.0
  CITATION.cff
  setup.cfg
  src/conda/meta.yaml
  src/setup.py
Labels: admin
