Repository fhswf/MLPro, pull requests merged in 2023-04, with the labels that each got.

#695 RTD: Typos, Class Diagram SL
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer0_elementary/03_persistence.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/01_basics.rst
Labels: bug, documentation

#706 RTD-OA: Activation and initial structure
  doc/rtd/content/00_start_page/images/mlpro_oa.png
  doc/rtd/content/00_start_page/images/variants/v7/.$icons intro.drawio.bkp
  doc/rtd/content/00_start_page/images/variants/v7/icons intro.drawio
  doc/rtd/content/01_welcome/sub/01_introduction.rst
  doc/rtd/content/01_welcome/sub/images/MLPro_Architecture.drawio
  doc/rtd/content/01_welcome/sub/images/MLPro_Architecture.drawio.png
  doc/rtd/content/03_machine_learning/mlpro_oa/main.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/01_overview.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/02_getstarted.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/03_oa_stream_processing.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/04_oa_systems.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/.gitkeep
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer1_oa_systems/.gitkeep
  doc/rtd/index.rst
Labels: documentation, enhancement, OA, v1.2.0

#707 SL: Refactoring PyTorch's Helper Functions
  src/mlpro/bf/math/basics.py
  src/mlpro/sl/pool/afct/pytorch.py
Labels: quality, refactoring, SL, next release, v1.2.0

#713 WR: Add Offscreen Viewer MuJoCo and Camera Functionality
  src/mlpro/wrappers/mujoco.py
Labels: enhancement, WR

#714 WR: Add Gymnasium Wrapper
  doc/rtd/content/01_welcome/sub/deps.txt
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/07_wrapper.rst
  doc/rtd/content/04_appendices/appendix1/sub/mlpro_rl/wp/howto.rl.wp.007.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/gymnasium.rst
  requirements.txt
  setup.cfg
  src/mlpro/bf/plot.py
  src/mlpro/rl/examples/howto_rl_wp_007_gymnasium_environment_to_mlpro_environment.py
  src/mlpro/wrappers/gymnasium.py
  test/test_examples.py
Labels: enhancement, WR, next release, v1.2.0

#722 RTD-BF-Streams: Documentation for 3rd Party Support
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/streams/04_third_party_support.rst
  doc/rtd/content/04_appendices/appendix1/sub/mlpro_bf/layer3_application_support/streams/howto.bf.streams.051.rst
Labels: documentation, BF, v1.2.0

#721 BF: Add howto examples MuJoCo with image from camera
  .gitignore
  src/mlpro/bf/examples/howto_bf_systems_004_box_on_table_mujoco_simulation.py
  src/mlpro/bf/systems/basics.py
  src/mlpro/bf/systems/pool/mujoco/boxontable.xml
  src/mlpro/wrappers/mujoco.py
Labels: BF, next release

#727 WR: Add MuJoCo camera fovy to state
  src/mlpro/wrappers/mujoco.py
Labels: enhancement, WR, next release, v1.2.0

#737 Admin: CI Optimization
  .github/workflows/ci.yml
  .readthedocs.yaml
  doc/rtd/content/01_welcome/sub/deps.txt
  doc/rtd/requirements.txt
  requirements.txt
  setup.cfg
Labels: admin, review, refactoring, v1.2.0

#741 WR: Gym removal, SB3 update to 2.0 alpha
  .github/workflows/ci.yml
  doc/rtd/content/01_welcome/sub/deps.txt
  doc/rtd/requirements.txt
  requirements.txt
  setup.cfg
  src/mlpro/rl/examples/howto_rl_agent_001_run_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_002_train_agent_with_own_policy_on_gym_environment.py
  src/mlpro/rl/examples/howto_rl_agent_011_train_and_reload_single_agent_gym.py
  src/mlpro/rl/examples/howto_rl_att_001_train_and_reload_single_agent_gym_sd.py
  src/mlpro/rl/examples/howto_rl_mb_001_train_and_reload_model_based_agent_gym.py
  src/mlpro/rl/examples/howto_rl_wp_001_mlpro_environment_to_gym_environment.py
  src/mlpro/rl/examples/howto_rl_wp_004_train_agent_with_sb3_policy.py
  src/mlpro/rl/examples/howto_rl_wp_005_validation_wrapped_sb3_on_policy.py
  src/mlpro/rl/examples/howto_rl_wp_006_validation_wrapped_sb3_off_policy.py
  src/mlpro/rl/examples/howto_rl_wp_007_gymnasium_environment_to_mlpro_environment.py
  src/mlpro/rl/pool/envs/gridworld.py
  src/mlpro/rl/pool/envs/multicartpole.py
  src/mlpro/wrappers/gymnasium.py
  src/mlpro/wrappers/openai_gym.py
  src/mlpro/wrappers/sb3.py
  test/test_buffer.py
  test/test_environment.py
  test/test_pool_policies.py
  test/test_sb3_policy_wrapper.py
Labels: quality, RL, WR, v1.2.0

#742 RTD: Refactoring API References
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_gt/01_basics.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_oa/01_streams.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_oa/images/.$MLPro-OA-Proc_class_diagram.drawio.bkp
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_rl/01_environments.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_rl/02_env_models.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_rl/11_agents.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_rl/21_scenarios_training.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/01_basics.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/02_fnn.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/samplers/min_wise.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/samplers/random.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/samplers/reservoir.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/samplers/weighted_random.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/streams/clouds2d_static.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/streams/clouds3d_static.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/streams/csv_file.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/streams/doublespiral2d.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/streams/rnd10d.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/tasks/deriver.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/tasks/rearranger.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/tasks/windows.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_bf/bf_systems/01_double_pendulum_native_system.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_gt/game_boards/bglp.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_gt/game_boards/multi_cartpole.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/action_planners/mpc.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/environments/bglp.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/environments/double_pendulum.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/environments/grid_world.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/environments/multi_cartpole.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/environments/robot_manipulator.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/policies/dummy.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/policies/random.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/sars_buffers/prioritizedbuffer.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_rl/sars_buffers/randomsarsbuffer.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/afct/afct_fnn_pytorch_mlp.rst
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/afct/afct_pytorch.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/gymnasium.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/hyperopt.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/mujoco.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/openai_gym.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/openml.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/optuna.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/pettingzoo.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/river.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/sb3.rst
  doc/rtd/content/04_appendices/appendix2/sub/wrappers/sklearn.rst
Labels: documentation, refactoring, next release
