Repository fhswf/MLPro, pull requests merged in 2023-03, with the labels that each got.

#640 SL: Supervised Learning1
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_bf/layer3_application_support/images/.$MLPro-BF-Systems_class_diagram.drawio.bkp
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Basics_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Brainstorm_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-FNN_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-FNN_class_diagram.drawio.png
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-basics_class_diagram.drawio.png
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL_class_diagram.drawio.png
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/images/MLPro-SL-pool-afct-fnn-pytorch_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/images/MLPro-SL-pool-afct-fnn-pytorch_class_diagram.drawio.png
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/images/MLPro-SL-pool-afct-pytorch_class_diagram.drawio
  doc/rtd/content/04_appendices/appendix2/sub/pool/mlpro_sl/images/MLPro-SL-pool-afct-pytorch_class_diagram.drawio.png
  src/mlpro/bf/math/basics.py
  src/mlpro/rl/examples/howto_rl_mb_001_robothtm_environment.py
  src/mlpro/rl/examples/howto_rl_mb_002_grid_world_environment.py
  src/mlpro/rl/pool/envmodels/htm_robotinhtm.py
  src/mlpro/rl/pool/envmodels/mlp_gridworld.py
  src/mlpro/rl/pool/envmodels/mlp_robotinhtm.py
  src/mlpro/sl/__init__.py
  src/mlpro/sl/basics.py
  src/mlpro/sl/fnn.py
  src/mlpro/sl/pool/afct/afct_pytorch.py
  src/mlpro/sl/pool/afct/fnn/__init__.py
  src/mlpro/sl/pool/afct/fnn/pytorch/mlp.py
  src/mlpro/sl/pool/afct/pytorch.py
Labels: documentation, enhancement, v1.0.0, SL

#667 SL: Add missing _init_ in MLPro-SL
  src/mlpro/sl/pool/afct/fnn/pytorch/__init__.py
Labels: bug, SL, next release

#668 WR : Added MuJoCo XML in MANIFEST.in
  MANIFEST.in
Labels: WR, v1.0.1

#681 RTD: Bugfix of Control Element for Version Selection
  doc/rtd/conf.py
Labels: bug, documentation, v1.1.0

#684 Add anaconda download badges on Readme
  README.md
Labels: documentation

#686 BF: Repositioning xyz arrow in MuJoCo
  src/mlpro/bf/systems/pool/mujoco/mlpro.xml
  src/mlpro/wrappers/mujoco.py
Labels: enhancement, BF, v1.1.0
