Repository fhswf/MLPro, pull requests merged in 2023-01, with the labels that each got.

#581 Installation option for mlpro "full"
  .github/workflows/ci.yml
  setup.cfg
  src/setup.py
Labels: enhancement, admin

#583 New class TransferFunction
  src/mlpro/bf/examples/howto_bf_math_020_unit_converter.py
  src/mlpro/bf/examples/howto_bf_systems_002_set_up_transfer_functions.py
  src/mlpro/bf/math/unitconverter.py
  src/mlpro/bf/systems.py
  src/mlpro/bf/various.py
  test/test_examples.py
Labels: documentation, enhancement, BF, next release

#558 BF-Streams: Extensions
  doc/rtd/content/append2/core/images/bf/.$MLPro-BF-Streams_class_diagram.drawio.bkp
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-MT_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Math_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Plot_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio
  doc/rtd/content/append2/core/images/bf/MLPro-BF-Streams_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio
  doc/rtd/content/append2/core/images/oa/MLPro-OA-Proc_class_diagram.drawio.png
  doc/rtd/content/append2/core/images/rl/01_environments/MLPro-RL-Env-AdaptiveEnvironment_class_diagram.drawio
  src/mlpro/bf/examples/howto_bf_streams_001_accessing_native_data_from_mlpro.py
  src/mlpro/bf/examples/howto_bf_streams_101_basics.py
  src/mlpro/bf/examples/howto_bf_streams_102_xxx.py
  src/mlpro/bf/examples/howto_bf_streams_103_stream_task_window.py
  src/mlpro/bf/examples/howto_bf_streams_110_stream_task_window.py
  src/mlpro/bf/examples/howto_bf_streams_111_stream_task_rearranger_2d.py
  src/mlpro/bf/examples/howto_bf_streams_112_stream_task_rearranger_3d.py
  src/mlpro/bf/examples/howto_bf_streams_113_stream_task_rearranger_nd.py
  src/mlpro/bf/math/basics.py
  src/mlpro/bf/math/normalizers.py
  src/mlpro/bf/ml.py
  src/mlpro/bf/mt.py
  src/mlpro/bf/plot.py
  src/mlpro/bf/streams/__init__.py
  src/mlpro/bf/streams/models.py
  src/mlpro/bf/streams/streams/__init__.py
  src/mlpro/bf/streams/streams/clouds2d_static.py
  src/mlpro/bf/streams/streams/clouds3d_static.py
  src/mlpro/bf/streams/streams/doublespiral2d.py
  src/mlpro/bf/streams/streams/provider_mlpro.py
  src/mlpro/bf/streams/streams/rnd10d.py
  src/mlpro/bf/streams/tasks/__init__.py
  src/mlpro/bf/streams/tasks/rearranger.py
  src/mlpro/bf/streams/tasks/windows.py
  src/mlpro/oa/examples/howto_oa_pp_001_normalization_of_streamed_data_minmax.py
  src/mlpro/oa/examples/howto_oa_pp_002_normalization_of_streamed_data_ztransform.py
  src/mlpro/oa/examples/howto_oa_pp_003_rearranger_window_bd_normminmax_2d.py
  src/mlpro/oa/examples/howto_oa_pp_004_rearranger_window_bd_normminmax_3d.py
  src/mlpro/oa/examples/howto_oa_pp_005_rearranger_window_bd_normminmax_nd.py
  src/mlpro/oa/models.py
  src/mlpro/oa/tasks/__init__.py
  src/mlpro/oa/tasks/boundarydetectors.py
  src/mlpro/oa/tasks/normalizers.py
  src/mlpro/wrappers/sklearn.py
  test/test_examples.py
Labels: enhancement, OA, BF, next release

#588 BF: Debugging on TransferFunction and UnitConverter
  src/mlpro/bf/math/unitconverter.py
  src/mlpro/bf/systems.py
Labels: enhancement, v1.0.0, BF
