Repository fhswf/MLPro, pull requests merged in 2023-02, with the labels that each got.

#571 RL: Add multi-processing on MPC
  src/mlpro/rl/examples/howto_rl_mb_002_grid_world_environment.py
  src/mlpro/rl/models_agents.py
  src/mlpro/rl/pool/actionplanner/mpc.py
Labels: enhancement, v2.0.0, RL

#586 Quality Assurance v1.0.0
  doc/rtd/content/01_welcome/sub/deps.txt
  requirements.txt
  setup.cfg
  src/mlpro/bf/data.py
  src/mlpro/bf/events.py
  src/mlpro/bf/examples/howto_bf_ml_001_adaptive_model.py
  src/mlpro/bf/examples/howto_bf_ml_010_hyperparameters.py
  src/mlpro/bf/examples/howto_bf_systems_002_systems_wrapped_with_mujoco.py
  src/mlpro/bf/math/normalizers.py
  src/mlpro/bf/ml/basics.py
  src/mlpro/bf/mt.py
  src/mlpro/bf/systems/basics.py
  src/mlpro/bf/systems/pool/mujoco/__init__.py
  src/mlpro/bf/systems/pool/mujoco/assets/doublependulum.xml
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/base.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/forearm.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/shoulder.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/upperarm.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/wrist1.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/wrist2.stl
  src/mlpro/bf/systems/pool/mujoco/assets/mesh/wrist3.stl
  src/mlpro/bf/systems/pool/mujoco/assets/pendulum.xml
  src/mlpro/bf/systems/pool/mujoco/assets/ur5.xml
  src/mlpro/rl/examples/howto_rl_agent_005_train_and_reload_single_agent.py
  src/mlpro/rl/examples/howto_rl_env_007_run_agent_with_random_policy_on_double_pendulum_mujoco_environment.py
  src/mlpro/rl/examples/howto_rl_mb_002_grid_world_environment.py
  src/mlpro/rl/examples/howto_rl_pp_001_train_agent_with_sb3_policy_on_ur5_environment.py
  src/mlpro/rl/examples/howto_rl_pp_002_load_and_run_ur5_environment.py
  src/mlpro/rl/examples/howto_rl_wp_004_train_agent_with_sb3_policy.py
  src/mlpro/rl/examples/howto_rl_wp_005_validation_wrapped_sb3_on_policy.py
  src/mlpro/rl/examples/howto_rl_wp_006_validation_wrapped_sb3_off_policy.py
  src/mlpro/rl/models_env.py
  src/mlpro/wrappers/mujoco.py
  test/test_examples.py
Labels: quality, v1.0.0

#624 RTD: Final Documentation v1.0.0-2
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/04_layer2_mathematics.rst
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/images/MLPro-BF-MATH_Basics.drawio
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/images/MLPro-BF-MATH_Basics.drawio.png
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/images/bf-math.png
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/02_pyhsics.rst
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/01_transferfunction.rst
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/02_unitconverter.rst
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/images/bf_physics_transferlearning.drawio
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/images/bf_physics_transferlearning.drawio.png
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/images/bf_physics_unitconverter.drawio
  doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/physics/images/bf_physics_unitconverter.drawio.png
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_bf/layer3_application_support/02_pyhsics.rst
  doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_bf/layer3_application_support/03_physics_unitconverter.rst
  doc/rtd/index.rst
Labels: documentation, v1.0.0
