Repository fhswf/MLPro, pull requests merged in 2024-08, with the labels that each got.

#1029 OA: Cluster analysis - updates, corrections, improvements (9)
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/gameboard/rlenvs.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/gettingstarted/01_native.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/gettingstarted/02_dg.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/03_oa_stream_processing.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview/01_oa_stream_task.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview/02_oa_stream_workflow.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/02_oa_boundary_detector.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization/01_oa_minmax.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization/02_oa_zscaling.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/10_cluster_analysis.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/10_cluster_analysis/.gitkeep
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/20_anomaly_detection.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/20_anomaly_detection/01_cbad.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/30_anomaly_prediction.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/30_anomaly_prediction/.gitkeep
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/02_getstarted.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/03_env.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/05_scenario.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/06_train.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/custompolicies.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/mbagents.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/multiagents.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/pool/mpc.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/customenv.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/2Dcollisiondetection.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/doublependulum.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/gridworld.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_1.gif
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_2.png
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_3.png
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/multicartpole.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/robotmanipulator.rst
  doc/rtd/content/03_machine_learning/mlpro_sl/sub/02_getstarted.rst
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/04_anomaly_predictors.rst
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Predictors.class_diagram.drawio.png
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Predictors_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/pool/mlpro_rl/environments/2Dcollisiondetection.rst
  src/mlpro/bf/math/geometry/__init__.py
  src/mlpro/bf/math/geometry/hypercuboid.py
  src/mlpro/bf/math/properties.py
  src/mlpro/oa/streams/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/properties/centroid.py
  src/mlpro/rl/pool/envs/collisionavoidance_2D.py
Labels: OA

#1027 RTD: V2.0.0
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/gameboard/rlenvs.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/gettingstarted/01_native.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/gettingstarted/02_dg.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/03_oa_stream_processing.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview/01_oa_stream_task.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/01_overview/02_oa_stream_workflow.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/02_oa_boundary_detector.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization/01_oa_minmax.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/03_oa_normalization/02_oa_zscaling.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/10_cluster_analysis.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/10_cluster_analysis/.gitkeep
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/20_anomaly_detection.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/20_anomaly_detection/01_cbad.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/30_anomaly_prediction.rst
  doc/rtd/content/03_machine_learning/mlpro_oa/sub/layer0_oa_stream_processing/30_anomaly_prediction/.gitkeep
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/02_getstarted.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/03_env.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/05_scenario.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/06_train.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/custompolicies.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/mbagents.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/multiagents.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/agents/pool/mpc.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/customenv.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/2Dcollisiondetection.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/doublependulum.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/gridworld.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_1.gif
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_2.png
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/images/2Dcollisionavoidance_3.png
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/multicartpole.rst
  doc/rtd/content/03_machine_learning/mlpro_rl/sub/env/pool/robotmanipulator.rst
  doc/rtd/content/03_machine_learning/mlpro_sl/sub/02_getstarted.rst
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/04_anomaly_predictors.rst
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Predictors.class_diagram.drawio.png
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Predictors_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/pool/mlpro_rl/environments/2Dcollisiondetection.rst
  src/mlpro/rl/pool/envs/collisionavoidance_2D.py
Labels: documentation

#1038 RTD v2.0.0
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/.$MLPro-OA_Anomaly_Detectors_class_diagram.drawio.bkp
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Detectors_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Detectors_class_diagram.drawio.png
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_oa/streams/tasks/images/MLPro-OA_Anomaly_Detectors_class_diagram_simplified.drawio
Labels: documentation

#1041 BF: Hypercuboid - Collision detection #1040
  src/mlpro/bf/math/geometry/hypercuboid.py
Labels: BF
