Repository fhswf/MLPro, pull requests merged in 2024-04, with the labels that each got.

#933 OA: Anomaly Detection
  src/mlpro/bf/streams/streams/clouds.py
  src/mlpro/oa/streams/tasks/ad/anomaly_detector.py
  src/mlpro/oa/streams/tasks/ad/cluster_analyzer.py
  src/mlpro/oa/streams/tasks/ad/cluster_generator.py
  src/mlpro/oa/streams/tasks/anomalydetectors.py
  test/howtos/oa/howto_oa_ad_001_oneclasssvm.py
Labels: OA

#938 OA: Refactoring of Cluster Analysis/Anomaly Detection
  src/mlpro/bf/streams/streams/clouds_with_anomalies.py
  src/mlpro/oa/streams/tasks/ad/anomaly_detector.py
  src/mlpro/oa/streams/tasks/ad/cluster_analyzer.py
  src/mlpro/oa/streams/tasks/anomalydetectors.py
  src/mlpro/oa/streams/tasks/anomalydetectors/__init__.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/__init__.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/basics.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/clusterbasedanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/contextualanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/driftanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/groupanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/pointanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/basics.py
  src/mlpro/oa/streams/tasks/anomalydetectors/cb_detectors.py
  src/mlpro/oa/streams/tasks/anomalydetectors/paga_detectors.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/__init__.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/__init__.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/centroid.py
Labels: OA

#940 OA: Visualization of anomalies
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/__init__.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/basics.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/clusterbased.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/contextual.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/drift.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/group.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/point.py
  src/mlpro/oa/streams/tasks/anomalydetectors/anomalies/pointanomaly.py
  src/mlpro/oa/streams/tasks/anomalydetectors/basics.py
Labels: OA

#949 Refact: Parameter p_outlier_frequency of Class StreamMLProPOutliers s…
  src/mlpro/bf/streams/streams/point_outliers.py
  test/howtos/bf/howto_bf_streams_005_native_stream_PointOutliersND.py
Labels: BF

#772 SL: Initial Design
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Basics_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Models_Dataset.drawio
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Models_Evaluation.drawio
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_sl/images/MLPro-SL-Models_training.drawio
  src/mlpro/bf/datasets/basics.py
  src/mlpro/sl/basics.py
  src/mlpro/sl/examples/howto_sl_afct_100_train_and_reload_pytorch_mlp.py
Labels: SL

#950 BF: General systematics for properties (and their derivatives) #943
  src/mlpro/bf/data/__init__.py
  src/mlpro/bf/data/buffers.py
  src/mlpro/bf/data/datastoring.py
  src/mlpro/bf/data/properties.py
  test/howtos/bf/howto_bf_003_store_plot_and_save_variables.py
  test/howtos/bf/howto_bf_004_buffers.py
  test/howtos/bf/howto_bf_data_011_properties_with_implicite_time_index.py
  test/howtos/bf/howto_bf_data_012_properties_with_explicite_integer_time_index.py
  test/howtos/bf/howto_bf_data_013_properties_with_explicite_datetime_index.py
Labels: BF

#955 Refact: Class bf.math.geometry.Point - Replace parent bf.math.Element…
  src/mlpro/bf/data/properties.py
  src/mlpro/bf/math/geometry.py
  test/howtos/bf/howto_bf_data_011_properties_with_implicite_time_index.py
  test/howtos/bf/howto_bf_data_012_properties_with_explicite_integer_time_index.py
  test/howtos/bf/howto_bf_data_013_properties_with_explicite_datetime_index.py
  test/howtos/bf/howto_bf_math_020_geometry_point_2d.py
  test/howtos/bf/howto_bf_math_021_geometry_point_3d.py
Labels: BF

#956 Refact: Class bf.math.geometry.Point - Replace parent bf.math.Element(2)
  src/mlpro/bf/math/geometry.py
Labels: quality, refactoring, BF

#953 OA: Cluster Analysis
  src/mlpro/bf/math/geometry.py
  src/mlpro/bf/math/normalizers.py
  src/mlpro/bf/math/normalizers/__init__.py
  src/mlpro/bf/math/normalizers/basics.py
  src/mlpro/bf/math/normalizers/minmax.py
  src/mlpro/bf/math/normalizers/ztrans.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/basics.py
  src/mlpro/oa/streams/tasks/clusteranalyzers/clusters/centroid.py
  test/howtos/bf/howto_bf_math_010_normalizers.py
Labels: OA
