Repository fhswf/MLPro, pull requests merged in 2024-07, with the labels that each got.

#1025 OA: Cluster analysis - updates, corrections, improvements (8)
  src/mlpro/bf/math/geometry/hypercuboid.py
  src/mlpro/bf/math/properties.py
Labels: OA

#1026 RL: New Environment - Trajectory Planning
  src/mlpro/bf/plot.py
  src/mlpro/rl/pool/envs/collisionavoidance_2D.py
Labels: enhancement, RL

#1030 Refact: Normalizer MinMax
  src/mlpro/bf/math/normalizers/basics.py
  src/mlpro/bf/math/normalizers/minmax.py
  src/mlpro/oa/streams/tasks/normalizers/minmax.py
  test/howtos/oa/howto_oa_streams_pp_001_bd_normminmax_2d.py
Labels: BF

#1032 OA: Refactoring Streams
  doc/rtd/content/99_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/tasks/images/MLPro-BF-Streams-Tasks-Deriver_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/pool/mlpro_bf/bf_streams/tasks/images/MLPro-BF-Streams-Tasks-Deriver_class_diagram.drawio.png
  src/mlpro/bf/streams/tasks/deriver.py
  test/howtos/bf/howto_bf_streams_131_stream_task_deriver.py
  test/howtos/oa/howto_oa_streams_pp_121_complex_preprocessing.py
Labels: OA, BF

#1034 BF-Streams: Corrections on stream visualization
  src/mlpro/bf/streams/basics.py
Labels: BF
