Repository fhswf/MLPro, pull requests merged in 2024-02, with the labels that each got.

#914 Bug: Recovery of wrappers and howtos for River and Scikit-learn #913
  src/mlpro/wrappers/river/__init__.py
  src/mlpro/wrappers/river/anomalydetectors.py
  src/mlpro/wrappers/river/basics.py
  src/mlpro/wrappers/river/clusteranalyzers.py
  src/mlpro/wrappers/river/streams.py
  src/mlpro/wrappers/sklearn/__init__.py
  src/mlpro/wrappers/sklearn/anomalydetectors.py
  src/mlpro/wrappers/sklearn/basics.py
  test/howtos/bf/howto_bf_streams_052_accessing_data_from_scikitlearn.py
  test/howtos/bf/howto_bf_streams_053_accessing_data_from_river.py
Labels: bug, WR

#915 BF-Streams: New native benchmark stream for point outliers #911
  src/mlpro/bf/streams/streams/__init__.py
  src/mlpro/bf/streams/streams/point_outliers.py
  test/howtos/bf/howto_bf_streams_010_point_outliers.py
Labels: enhancement, BF

#918 Refact: Consolidation of native streams #916
  src/mlpro/bf/streams/streams/__init__.py
  src/mlpro/bf/streams/streams/clouds.py
  src/mlpro/bf/streams/streams/clouds2d_dynamic.py
  src/mlpro/bf/streams/streams/clouds2d_static.py
  src/mlpro/bf/streams/streams/clouds3d_dynamic.py
  src/mlpro/bf/streams/streams/clouds3d_static.py
  src/mlpro/bf/streams/streams/doublespiral2d.py
  templates/new_howto/howto_bf_zz_999_description.py
  templates/new_module/module.py
  test/howtos/bf/howto_bf_streams_001_accessing_native_data_from_mlpro.py
  test/howtos/bf/howto_bf_streams_002_accessing_data_from_csv_files.py
  test/howtos/bf/howto_bf_streams_003_native_stream_Rnd10Dx1000.py
  test/howtos/bf/howto_bf_streams_003_visualize_moving_clouds2d.py
  test/howtos/bf/howto_bf_streams_004_native_stream_DoubleSpiral2D.py
  test/howtos/bf/howto_bf_streams_004_visualize_moving_clouds3d.py
  test/howtos/bf/howto_bf_streams_005_native_stream_PointOutliersND.py
  test/howtos/bf/howto_bf_streams_006_native_stream_Clouds2D4C1000Static.py
  test/howtos/bf/howto_bf_streams_007_native_stream_Clouds2D4C5000Dynamic.py
  test/howtos/bf/howto_bf_streams_008_native_stream_Clouds3D8C2000Static.py
  test/howtos/bf/howto_bf_streams_009_native_stream_Clouds3D8C10000Dynamic.py
  test/howtos/bf/howto_bf_streams_010_native_stream_CloudsNDim.py
  test/howtos/bf/howto_bf_streams_010_point_outliers.py
  test/howtos/bf/howto_bf_streams_020_sampler.py
Labels: quality, refactoring, BF

#920 Refact: Consolidation of native streams #916
  src/mlpro/bf/streams/streams/clouds.py
Labels: quality, refactoring, BF

#932 Bug: Visualization of a cluster needs to be removed when cluster itse…
  src/mlpro/bf/math/geometry.py
  src/mlpro/bf/plot.py
  src/mlpro/oa/streams/tasks/clusteranalyzers.py
Labels: OA

#789 BF-ML : Hyperparameter Handling
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_bf/layer4_machine_learning/images/MLPro-BF-ML_class_diagram.drawio
  doc/rtd/content/99_appendices/appendix2/sub/core/mlpro_bf/layer4_machine_learning/images/MLPro-BF-ML_class_diagram.drawio.png
  src/mlpro/bf/ml/basics.py
Labels: BF
