Repository fhswf/MLPro, pull requests merged in 2025-04, with the labels that each got.

#1177 GT: Gradient-based Learning in SbPGs
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/gameboard/customgb.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/games.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/players/pool.rst
  doc/rtd/content/03_machine_learning/mlpro_gt/sub/dg/players/pool/sbpg.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_gt/dg/howto.gt.dg.001.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_gt/dg/howto.gt.dg.002.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_gt/dg/howto.gt.dg.003.rst
  doc/rtd/content/99_appendices/appendix1/sub/mlpro_gt/dg/howto.gt.dg.004.rst
  doc/rtd/content/99_appendices/appendix2/sub/mlpro_gt/pool/dg/02_policies.rst
  doc/rtd/content/99_appendices/appendix2/sub/mlpro_gt/pool/dg/policies/sbpg.rst
  doc/rtd/content/99_appendices/appendix2/sub/mlpro_rl/pool/03_policies.rst
  doc/rtd/content/99_appendices/appendix3/sub/02_publications.rst
  src/mlpro/gt/pool/policies/sbpg.py
  test/howtos/gt/howto_gt_dg_003_train_multi_player_with_SbPG_on_BGLP.py
Labels: enhancement, GT

#1181 Hotfix v2.0.1
  .github/workflows/conda_deploy.yml
  .github/workflows/pypi_deploy.yml
  conda-recipe/conda_build_config.yaml
  conda-recipe/meta.yaml
  doc/rtd/content/00_start_page/images/anaconda.png
  doc/rtd/content/01_welcome/sub/02_getting_started.rst
  doc/rtd/index.rst
  src/mlpro/oa/streams/tasks/clusteranalyzers/basics.py
Labels: OA

#1182 Hotfix v2.0.1 (2)
  doc/rtd/index.rst
Labels: admin
